@echo off
set date="%date:~4,2%-%date:~7,2%-%date:~10,4%"
set path="\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\CPLogs\"
mkdir ""\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\Ingenico\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\CPLogs\"
mkdir ""\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\Ingenico\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\CPLogs\"
mkdir ""\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\Ingenico\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\CPLogs\"
mkdir ""\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\Ingenico\"
xcopy \\bp-vm-cpx201\CounterPointSQL\Logs\CPLogs "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\CPLogs" /E
xcopy \\bp-vm-cpx201\CounterPointSQL\Logs\Ingenico "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\Ingenico" /E
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP0114R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP0116R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP0121R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP0457R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP0842R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CounterPoint_BP05*R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx201\"
xcopy \\bp-vm-cpx202\CounterPointSQL\Logs\CPLogs "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\CPLogs" /E
xcopy \\bp-vm-cpx202\CounterPointSQL\Logs\Ingenico "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\Ingenico" /E
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP0114R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP0116R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP0121R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP0457R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP0842R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CounterPoint_BP05*R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx202\"
xcopy \\bp-vm-cpx203\CounterPointSQL\Logs\CPLogs "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\CPLogs" /E
xcopy \\bp-vm-cpx203\CounterPointSQL\Logs\Ingenico "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\Ingenico" /E
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP0114R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP0116R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP0121R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP0457R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP0842R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CounterPoint_BP05*R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx203\"
xcopy \\bp-vm-cpx204\CounterPointSQL\Logs\CPLogs "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\CPLogs" /E
xcopy \\bp-vm-cpx204\CounterPointSQL\Logs\Ingenico "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\Ingenico" /E
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP0114R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP0116R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP0121R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP0457R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP0456R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP0842R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CounterPoint_BP05*R*.* "\\bph-fs01\PUBLIC\NetworkOperations\CP Logs\%date%\bp-vm-cpx204\"