@echo off
set date="%date:~4,2%-%date:~7,2%-%date:~10,4%"
set path="\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\CPLogs\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\Ingenico\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\CPLogs\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\Ingenico\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\CPLogs\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\Ingenico\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\CPLogs\"
mkdir "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\Ingenico\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CPLogs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\CPlogs\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CPLogs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\CPlogs\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CPLogs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\CPlogs\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CPLogs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\CPlogs\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CPLogs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\CPlogs\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\CPLogs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\CPlogs\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\Ingenico\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\Ingenico\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\Ingenico\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\Ingenico\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\Ingenico\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\Ingenico\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\Ingenico\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\Ingenico\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\Ingenico\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\Ingenico\"
copy \\bp-vm-cpx201\CounterPointSQL\Logs\Ingenico\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx201\Ingenico\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CPLogs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\CPlogs\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CPLogs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\CPlogs\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CPLogs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\CPlogs\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CPLogs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\CPlogs\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CPLogs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\CPlogs\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\CPLogs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\CPlogs\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\Ingenico\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\Ingenico\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\Ingenico\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\Ingenico\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\Ingenico\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\Ingenico\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\Ingenico\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\Ingenico\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\Ingenico\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\Ingenico\"
copy \\bp-vm-cpx202\CounterPointSQL\Logs\Ingenico\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx202\Ingenico\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CPLogs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\CPlogs\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CPLogs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\CPlogs\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CPLogs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\CPlogs\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CPLogs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\CPlogs\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CPLogs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\CPlogs\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\CPLogs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\CPlogs\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\Ingenico\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\Ingenico\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\Ingenico\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\Ingenico\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\Ingenico\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\Ingenico\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\Ingenico\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\Ingenico\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\Ingenico\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\Ingenico\"
copy \\bp-vm-cpx203\CounterPointSQL\Logs\Ingenico\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx203\Ingenico\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CPLogs\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\CPlogs\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CPLogs\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\CPlogs\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CPLogs\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\CPlogs\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CPLogs\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\CPlogs\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CPLogs\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\CPlogs\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\CPLogs\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\CPlogs\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\Ingenico\*BP0121R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\Ingenico\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\Ingenico\*BP0502R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\Ingenico\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\Ingenico\*BP0507R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\Ingenico\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\Ingenico\*BP0508R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\Ingenico\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\Ingenico\*BP0558R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\Ingenico\"
copy \\bp-vm-cpx204\CounterPointSQL\Logs\Ingenico\*BP0573R*.log "\\bph-fs01\PUBLIC\NetworkOperations\CPlogs\%date%\bp-vm-cpx204\Ingenico\"