@ECHO OFF
ECHO Comparing CPX401 and CPX402...
fc /b \\bp-vm-cpx401\CounterPointSQL\Bin\*.* \\bp-vm-cpx402\CounterPointSQL\Bin\*.* > "Zone 4 CP Compare.txt"
ECHO Comparing CPX401 and CPX403...
fc /b \\bp-vm-cpx401\CounterPointSQL\Bin\*.* \\bp-vm-cpx403\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX401 and CPX404...
fc /b \\bp-vm-cpx401\CounterPointSQL\Bin\*.* \\bp-vm-cpx404\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX401 and CPX405...
fc /b \\bp-vm-cpx401\CounterPointSQL\Bin\*.* \\bp-vm-cpx405\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX401 and CPX406...
fc /b \\bp-vm-cpx401\CounterPointSQL\Bin\*.* \\bp-vm-cpx406\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX401 and CPX407...
fc /b \\bp-vm-cpx401\CounterPointSQL\Bin\*.* \\bp-vm-cpx407\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX401 and CPX408...
fc /b \\bp-vm-cpx401\CounterPointSQL\Bin\*.* \\bp-vm-cpx408\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX402 and CPX403...
fc /b \\bp-vm-cpx402\CounterPointSQL\Bin\*.* \\bp-vm-cpx403\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX402 and CPX404...
fc /b \\bp-vm-cpx402\CounterPointSQL\Bin\*.* \\bp-vm-cpx404\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX402 and CPX405...
fc /b \\bp-vm-cpx402\CounterPointSQL\Bin\*.* \\bp-vm-cpx405\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX402 and CPX406...
fc /b \\bp-vm-cpx402\CounterPointSQL\Bin\*.* \\bp-vm-cpx406\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX402 and CPX407...
fc /b \\bp-vm-cpx402\CounterPointSQL\Bin\*.* \\bp-vm-cpx407\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX402 and CPX408...
fc /b \\bp-vm-cpx402\CounterPointSQL\Bin\*.* \\bp-vm-cpx408\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX403 and CPX404...
fc /b \\bp-vm-cpx403\CounterPointSQL\Bin\*.* \\bp-vm-cpx404\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX403 and CPX405...
fc /b \\bp-vm-cpx403\CounterPointSQL\Bin\*.* \\bp-vm-cpx405\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX403 and CPX406...
fc /b \\bp-vm-cpx403\CounterPointSQL\Bin\*.* \\bp-vm-cpx406\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX403 and CPX407...
fc /b \\bp-vm-cpx403\CounterPointSQL\Bin\*.* \\bp-vm-cpx407\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX403 and CPX408...
fc /b \\bp-vm-cpx403\CounterPointSQL\Bin\*.* \\bp-vm-cpx408\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX404 and CPX405...
fc /b \\bp-vm-cpx404\CounterPointSQL\Bin\*.* \\bp-vm-cpx405\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX404 and CPX406...
fc /b \\bp-vm-cpx404\CounterPointSQL\Bin\*.* \\bp-vm-cpx406\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX404 and CPX407...
fc /b \\bp-vm-cpx404\CounterPointSQL\Bin\*.* \\bp-vm-cpx407\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX404 and CPX408...
fc /b \\bp-vm-cpx404\CounterPointSQL\Bin\*.* \\bp-vm-cpx408\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX405 and CPX406...
fc /b \\bp-vm-cpx405\CounterPointSQL\Bin\*.* \\bp-vm-cpx406\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX405 and CPX407...
fc /b \\bp-vm-cpx405\CounterPointSQL\Bin\*.* \\bp-vm-cpx407\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX405 and CPX408...
fc /b \\bp-vm-cpx405\CounterPointSQL\Bin\*.* \\bp-vm-cpx408\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX406 and CPX407...
fc /b \\bp-vm-cpx406\CounterPointSQL\Bin\*.* \\bp-vm-cpx407\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX406 and CPX408...
fc /b \\bp-vm-cpx406\CounterPointSQL\Bin\*.* \\bp-vm-cpx408\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"
ECHO Comparing CPX407 and CPX408...
fc /b \\bp-vm-cpx407\CounterPointSQL\Bin\*.* \\bp-vm-cpx408\CounterPointSQL\Bin\*.* >> "Zone 4 CP Compare.txt"