@ECHO OFF
ECHO Comparing CPX201 and CPX202...
fc /b \\bp-vm-cpx201\CounterPointSQL\Bin\*.* \\bp-vm-cpx202\CounterPointSQL\Bin\*.* > "Zone 2 CP Compare.txt"
ECHO Comparing CPX201 and CPX203...
fc /b \\bp-vm-cpx201\CounterPointSQL\Bin\*.* \\bp-vm-cpx203\CounterPointSQL\Bin\*.* >> "Zone 2 CP Compare.txt"
ECHO Comparing CPX201 and CPX204...
fc /b \\bp-vm-cpx201\CounterPointSQL\Bin\*.* \\bp-vm-cpx204\CounterPointSQL\Bin\*.* >> "Zone 2 CP Compare.txt"
ECHO Comparing CPX202 and CPX203...
fc /b \\bp-vm-cpx202\CounterPointSQL\Bin\*.* \\bp-vm-cpx203\CounterPointSQL\Bin\*.* >> "Zone 2 CP Compare.txt"
ECHO Comparing CPX202 and CPX204...
fc /b \\bp-vm-cpx202\CounterPointSQL\Bin\*.* \\bp-vm-cpx204\CounterPointSQL\Bin\*.* >> "Zone 2 CP Compare.txt"
ECHO Comparing CPX203 and CPX204...
fc /b \\bp-vm-cpx203\CounterPointSQL\Bin\*.* \\bp-vm-cpx204\CounterPointSQL\Bin\*.* >> "Zone 2 CP Compare.txt"