@ECHO OFF
ECHO Comparing CPX101 and CPX102...
fc /b \\bp-vm-cpx101\CounterPointSQL\Bin\*.* \\bp-vm-cpx102\CounterPointSQL\Bin\*.* > "Zone 1 CP Compare.txt"
ECHO Comparing CPX101 and CPX103...
fc /b \\bp-vm-cpx101\CounterPointSQL\Bin\*.* \\bp-vm-cpx103\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX101 and CPX104...
fc /b \\bp-vm-cpx101\CounterPointSQL\Bin\*.* \\bp-vm-cpx104\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX101 and CPX105...
fc /b \\bp-vm-cpx101\CounterPointSQL\Bin\*.* \\bp-vm-cpx105\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX101 and CPX106...
fc /b \\bp-vm-cpx101\CounterPointSQL\Bin\*.* \\bp-vm-cpx106\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX101 and CPX107...
fc /b \\bp-vm-cpx101\CounterPointSQL\Bin\*.* \\bp-vm-cpx107\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX101 and CPX108...
fc /b \\bp-vm-cpx101\CounterPointSQL\Bin\*.* \\bp-vm-cpx108\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX102 and CPX103...
fc /b \\bp-vm-cpx102\CounterPointSQL\Bin\*.* \\bp-vm-cpx103\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX102 and CPX104...
fc /b \\bp-vm-cpx102\CounterPointSQL\Bin\*.* \\bp-vm-cpx104\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX102 and CPX105...
fc /b \\bp-vm-cpx102\CounterPointSQL\Bin\*.* \\bp-vm-cpx105\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX102 and CPX106...
fc /b \\bp-vm-cpx102\CounterPointSQL\Bin\*.* \\bp-vm-cpx106\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX102 and CPX107...
fc /b \\bp-vm-cpx102\CounterPointSQL\Bin\*.* \\bp-vm-cpx107\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX102 and CPX108...
fc /b \\bp-vm-cpx102\CounterPointSQL\Bin\*.* \\bp-vm-cpx108\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX103 and CPX104...
fc /b \\bp-vm-cpx103\CounterPointSQL\Bin\*.* \\bp-vm-cpx104\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX103 and CPX105...
fc /b \\bp-vm-cpx103\CounterPointSQL\Bin\*.* \\bp-vm-cpx105\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX103 and CPX106...
fc /b \\bp-vm-cpx103\CounterPointSQL\Bin\*.* \\bp-vm-cpx106\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX103 and CPX107...
fc /b \\bp-vm-cpx103\CounterPointSQL\Bin\*.* \\bp-vm-cpx107\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX103 and CPX108...
fc /b \\bp-vm-cpx103\CounterPointSQL\Bin\*.* \\bp-vm-cpx108\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX104 and CPX105...
fc /b \\bp-vm-cpx104\CounterPointSQL\Bin\*.* \\bp-vm-cpx105\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX104 and CPX106...
fc /b \\bp-vm-cpx104\CounterPointSQL\Bin\*.* \\bp-vm-cpx106\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX104 and CPX107...
fc /b \\bp-vm-cpx104\CounterPointSQL\Bin\*.* \\bp-vm-cpx107\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX104 and CPX108...
fc /b \\bp-vm-cpx104\CounterPointSQL\Bin\*.* \\bp-vm-cpx108\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX105 and CPX106...
fc /b \\bp-vm-cpx105\CounterPointSQL\Bin\*.* \\bp-vm-cpx106\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX105 and CPX107...
fc /b \\bp-vm-cpx105\CounterPointSQL\Bin\*.* \\bp-vm-cpx107\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX105 and CPX108...
fc /b \\bp-vm-cpx105\CounterPointSQL\Bin\*.* \\bp-vm-cpx108\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX106 and CPX107...
fc /b \\bp-vm-cpx106\CounterPointSQL\Bin\*.* \\bp-vm-cpx107\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX106 and CPX108...
fc /b \\bp-vm-cpx106\CounterPointSQL\Bin\*.* \\bp-vm-cpx108\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"
ECHO Comparing CPX107 and CPX108...
fc /b \\bp-vm-cpx107\CounterPointSQL\Bin\*.* \\bp-vm-cpx108\CounterPointSQL\Bin\*.* >> "Zone 1 CP Compare.txt"