@ECHO OFF
ECHO Comparing CPX501 and CPX502...
fc /b \\bp-vm-cpx501\CounterPointSQL\Bin\*.* \\bp-vm-cpx502\CounterPointSQL\Bin\*.* > "Zone 5 CP Compare.txt"
ECHO Comparing CPX501 and CPX503...
fc /b \\bp-vm-cpx501\CounterPointSQL\Bin\*.* \\bp-vm-cpx503\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX501 and CPX504...
fc /b \\bp-vm-cpx501\CounterPointSQL\Bin\*.* \\bp-vm-cpx504\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX501 and CPX505...
fc /b \\bp-vm-cpx501\CounterPointSQL\Bin\*.* \\bp-vm-cpx505\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX501 and CPX506...
fc /b \\bp-vm-cpx501\CounterPointSQL\Bin\*.* \\bp-vm-cpx506\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX501 and CPX507...
fc /b \\bp-vm-cpx501\CounterPointSQL\Bin\*.* \\bp-vm-cpx507\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX501 and CPX508...
fc /b \\bp-vm-cpx501\CounterPointSQL\Bin\*.* \\bp-vm-cpx508\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX502 and CPX503...
fc /b \\bp-vm-cpx502\CounterPointSQL\Bin\*.* \\bp-vm-cpx503\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX502 and CPX504...
fc /b \\bp-vm-cpx502\CounterPointSQL\Bin\*.* \\bp-vm-cpx504\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX502 and CPX505...
fc /b \\bp-vm-cpx502\CounterPointSQL\Bin\*.* \\bp-vm-cpx505\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX502 and CPX506...
fc /b \\bp-vm-cpx502\CounterPointSQL\Bin\*.* \\bp-vm-cpx506\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX502 and CPX507...
fc /b \\bp-vm-cpx502\CounterPointSQL\Bin\*.* \\bp-vm-cpx507\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX502 and CPX508...
fc /b \\bp-vm-cpx502\CounterPointSQL\Bin\*.* \\bp-vm-cpx508\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX503 and CPX504...
fc /b \\bp-vm-cpx503\CounterPointSQL\Bin\*.* \\bp-vm-cpx504\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX503 and CPX505...
fc /b \\bp-vm-cpx503\CounterPointSQL\Bin\*.* \\bp-vm-cpx505\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX503 and CPX506...
fc /b \\bp-vm-cpx503\CounterPointSQL\Bin\*.* \\bp-vm-cpx506\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX503 and CPX507...
fc /b \\bp-vm-cpx503\CounterPointSQL\Bin\*.* \\bp-vm-cpx507\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX503 and CPX508...
fc /b \\bp-vm-cpx503\CounterPointSQL\Bin\*.* \\bp-vm-cpx508\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX504 and CPX505...
fc /b \\bp-vm-cpx504\CounterPointSQL\Bin\*.* \\bp-vm-cpx505\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX504 and CPX506...
fc /b \\bp-vm-cpx504\CounterPointSQL\Bin\*.* \\bp-vm-cpx506\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX504 and CPX507...
fc /b \\bp-vm-cpx504\CounterPointSQL\Bin\*.* \\bp-vm-cpx507\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX504 and CPX508...
fc /b \\bp-vm-cpx504\CounterPointSQL\Bin\*.* \\bp-vm-cpx508\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX505 and CPX506...
fc /b \\bp-vm-cpx505\CounterPointSQL\Bin\*.* \\bp-vm-cpx506\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX505 and CPX507...
fc /b \\bp-vm-cpx505\CounterPointSQL\Bin\*.* \\bp-vm-cpx507\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX505 and CPX508...
fc /b \\bp-vm-cpx505\CounterPointSQL\Bin\*.* \\bp-vm-cpx508\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX506 and CPX507...
fc /b \\bp-vm-cpx506\CounterPointSQL\Bin\*.* \\bp-vm-cpx507\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX506 and CPX508...
fc /b \\bp-vm-cpx506\CounterPointSQL\Bin\*.* \\bp-vm-cpx508\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"
ECHO Comparing CPX507 and CPX508...
fc /b \\bp-vm-cpx507\CounterPointSQL\Bin\*.* \\bp-vm-cpx508\CounterPointSQL\Bin\*.* >> "Zone 5 CP Compare.txt"