@ECHO OFF
ECHO Comparing CPX301 and CPX302...
fc /b \\bp-vm-cpx301\CounterPointSQL\Bin\*.* \\bp-vm-cpx302\CounterPointSQL\Bin\*.* > "Zone 3 CP Compare.txt"
ECHO Comparing CPX301 and CPX303...
fc /b \\bp-vm-cpx301\CounterPointSQL\Bin\*.* \\bp-vm-cpx303\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX301 and CPX304...
fc /b \\bp-vm-cpx301\CounterPointSQL\Bin\*.* \\bp-vm-cpx304\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX301 and CPX305...
fc /b \\bp-vm-cpx301\CounterPointSQL\Bin\*.* \\bp-vm-cpx305\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX301 and CPX306...
fc /b \\bp-vm-cpx301\CounterPointSQL\Bin\*.* \\bp-vm-cpx306\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX301 and CPX307...
fc /b \\bp-vm-cpx301\CounterPointSQL\Bin\*.* \\bp-vm-cpx307\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX301 and CPX308...
fc /b \\bp-vm-cpx301\CounterPointSQL\Bin\*.* \\bp-vm-cpx308\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX302 and CPX303...
fc /b \\bp-vm-cpx302\CounterPointSQL\Bin\*.* \\bp-vm-cpx303\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX302 and CPX304...
fc /b \\bp-vm-cpx302\CounterPointSQL\Bin\*.* \\bp-vm-cpx304\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX302 and CPX305...
fc /b \\bp-vm-cpx302\CounterPointSQL\Bin\*.* \\bp-vm-cpx305\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX302 and CPX306...
fc /b \\bp-vm-cpx302\CounterPointSQL\Bin\*.* \\bp-vm-cpx306\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX302 and CPX307...
fc /b \\bp-vm-cpx302\CounterPointSQL\Bin\*.* \\bp-vm-cpx307\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX302 and CPX308...
fc /b \\bp-vm-cpx302\CounterPointSQL\Bin\*.* \\bp-vm-cpx308\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX303 and CPX304...
fc /b \\bp-vm-cpx303\CounterPointSQL\Bin\*.* \\bp-vm-cpx304\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX303 and CPX305...
fc /b \\bp-vm-cpx303\CounterPointSQL\Bin\*.* \\bp-vm-cpx305\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX303 and CPX306...
fc /b \\bp-vm-cpx303\CounterPointSQL\Bin\*.* \\bp-vm-cpx306\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX303 and CPX307...
fc /b \\bp-vm-cpx303\CounterPointSQL\Bin\*.* \\bp-vm-cpx307\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX303 and CPX308...
fc /b \\bp-vm-cpx303\CounterPointSQL\Bin\*.* \\bp-vm-cpx308\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX304 and CPX305...
fc /b \\bp-vm-cpx304\CounterPointSQL\Bin\*.* \\bp-vm-cpx305\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX304 and CPX306...
fc /b \\bp-vm-cpx304\CounterPointSQL\Bin\*.* \\bp-vm-cpx306\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX304 and CPX307...
fc /b \\bp-vm-cpx304\CounterPointSQL\Bin\*.* \\bp-vm-cpx307\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX304 and CPX308...
fc /b \\bp-vm-cpx304\CounterPointSQL\Bin\*.* \\bp-vm-cpx308\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX305 and CPX306...
fc /b \\bp-vm-cpx305\CounterPointSQL\Bin\*.* \\bp-vm-cpx306\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX305 and CPX307...
fc /b \\bp-vm-cpx305\CounterPointSQL\Bin\*.* \\bp-vm-cpx307\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX305 and CPX308...
fc /b \\bp-vm-cpx305\CounterPointSQL\Bin\*.* \\bp-vm-cpx308\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX306 and CPX307...
fc /b \\bp-vm-cpx306\CounterPointSQL\Bin\*.* \\bp-vm-cpx307\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX306 and CPX308...
fc /b \\bp-vm-cpx306\CounterPointSQL\Bin\*.* \\bp-vm-cpx308\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"
ECHO Comparing CPX307 and CPX308...
fc /b \\bp-vm-cpx307\CounterPointSQL\Bin\*.* \\bp-vm-cpx308\CounterPointSQL\Bin\*.* >> "Zone 3 CP Compare.txt"