@ECHO OFF
ECHO Comparing CPX601 and CPX602...
fc /b \\bp-vm-cpx601\CounterPointSQL\Bin\*.* \\bp-vm-cpx602\CounterPointSQL\Bin\*.* > "Zone 6 CP Compare.txt"
ECHO Comparing CPX601 and CPX603...
fc /b \\bp-vm-cpx601\CounterPointSQL\Bin\*.* \\bp-vm-cpx603\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX601 and CPX604...
fc /b \\bp-vm-cpx601\CounterPointSQL\Bin\*.* \\bp-vm-cpx604\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX601 and CPX605...
fc /b \\bp-vm-cpx601\CounterPointSQL\Bin\*.* \\bp-vm-cpx605\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX601 and CPX606...
fc /b \\bp-vm-cpx601\CounterPointSQL\Bin\*.* \\bp-vm-cpx606\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX601 and CPX607...
fc /b \\bp-vm-cpx601\CounterPointSQL\Bin\*.* \\bp-vm-cpx607\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX601 and CPX608...
fc /b \\bp-vm-cpx601\CounterPointSQL\Bin\*.* \\bp-vm-cpx608\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX602 and CPX603...
fc /b \\bp-vm-cpx602\CounterPointSQL\Bin\*.* \\bp-vm-cpx603\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX602 and CPX604...
fc /b \\bp-vm-cpx602\CounterPointSQL\Bin\*.* \\bp-vm-cpx604\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX602 and CPX605...
fc /b \\bp-vm-cpx602\CounterPointSQL\Bin\*.* \\bp-vm-cpx605\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX602 and CPX606...
fc /b \\bp-vm-cpx602\CounterPointSQL\Bin\*.* \\bp-vm-cpx606\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX602 and CPX607...
fc /b \\bp-vm-cpx602\CounterPointSQL\Bin\*.* \\bp-vm-cpx607\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX602 and CPX608...
fc /b \\bp-vm-cpx602\CounterPointSQL\Bin\*.* \\bp-vm-cpx608\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX603 and CPX604...
fc /b \\bp-vm-cpx603\CounterPointSQL\Bin\*.* \\bp-vm-cpx604\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX603 and CPX605...
fc /b \\bp-vm-cpx603\CounterPointSQL\Bin\*.* \\bp-vm-cpx605\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX603 and CPX606...
fc /b \\bp-vm-cpx603\CounterPointSQL\Bin\*.* \\bp-vm-cpx606\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX603 and CPX607...
fc /b \\bp-vm-cpx603\CounterPointSQL\Bin\*.* \\bp-vm-cpx607\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX603 and CPX608...
fc /b \\bp-vm-cpx603\CounterPointSQL\Bin\*.* \\bp-vm-cpx608\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX604 and CPX605...
fc /b \\bp-vm-cpx604\CounterPointSQL\Bin\*.* \\bp-vm-cpx605\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX604 and CPX606...
fc /b \\bp-vm-cpx604\CounterPointSQL\Bin\*.* \\bp-vm-cpx606\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX604 and CPX607...
fc /b \\bp-vm-cpx604\CounterPointSQL\Bin\*.* \\bp-vm-cpx607\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX604 and CPX608...
fc /b \\bp-vm-cpx604\CounterPointSQL\Bin\*.* \\bp-vm-cpx608\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX605 and CPX606...
fc /b \\bp-vm-cpx605\CounterPointSQL\Bin\*.* \\bp-vm-cpx606\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX605 and CPX607...
fc /b \\bp-vm-cpx605\CounterPointSQL\Bin\*.* \\bp-vm-cpx607\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX605 and CPX608...
fc /b \\bp-vm-cpx605\CounterPointSQL\Bin\*.* \\bp-vm-cpx608\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX606 and CPX607...
fc /b \\bp-vm-cpx606\CounterPointSQL\Bin\*.* \\bp-vm-cpx607\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX606 and CPX608...
fc /b \\bp-vm-cpx606\CounterPointSQL\Bin\*.* \\bp-vm-cpx608\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"
ECHO Comparing CPX607 and CPX608...
fc /b \\bp-vm-cpx607\CounterPointSQL\Bin\*.* \\bp-vm-cpx608\CounterPointSQL\Bin\*.* >> "Zone 6 CP Compare.txt"